defmodule Acs.Repo.Migrations.AcsToolOperationsIdIdentity do
  use Ecto.Migration

  # SQLite integer PKs autoincrement; Postgres migration left id with no default,
  # so OperationLogger INSERTs (no id) failed silently and MetaHarness saw 0 ops.
  # Idempotent: may already be IDENTITY if applied manually on Neon during the audit.
  def up do
    if postgres?() do
      execute("""
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'acs_tool_operations'
            AND column_name = 'id'
            AND is_identity = 'NO'
        ) THEN
          ALTER TABLE acs_tool_operations
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
      END $$;
      """)
    end
  end

  def down do
    if postgres?() do
      execute("""
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'acs_tool_operations'
            AND column_name = 'id'
            AND is_identity = 'YES'
        ) THEN
          ALTER TABLE acs_tool_operations
            ALTER COLUMN id DROP IDENTITY IF EXISTS;
        END IF;
      END $$;
      """)
    end
  end

  defp postgres?, do: repo().__adapter__() == Ecto.Adapters.Postgres
end
