defmodule Acs.Repo.Migrations.AcsToolOperationsIdIdentity do
  use Ecto.Migration

  # SQLite integer PKs autoincrement; Postgres migration left id with no default,
  # so OperationLogger INSERTs (no id) failed silently and MetaHarness saw 0 ops.
  def up do
    if postgres?() do
      execute("""
      ALTER TABLE acs_tool_operations
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
      """)
    end
  end

  def down do
    if postgres?() do
      execute("""
      ALTER TABLE acs_tool_operations
        ALTER COLUMN id DROP IDENTITY IF EXISTS
      """)
    end
  end

  defp postgres?, do: repo().__adapter__() == Ecto.Adapters.Postgres
end
