#!/bin/sh
# Generate .env from pass password-store for Steward ACS.
# Usage:
#   ./scripts/secrets-env.sh                 # write .env securely (default)
#   ./scripts/secrets-env.sh -w .env.prod    # write a specific file
#   ./scripts/secrets-env.sh --stdout         # explicitly print secrets
set -e
umask 077

PREFIX="${PASS_PREFIX:-steward}"
PASS="${PASS:-pass}"
STORE="${PASSWORD_STORE_DIR:-$HOME/.password-store}"

write_to=".env"
case "${1:-}" in
  -w) write_to="${2:-.env}" ;;
  --stdout) write_to="" ;;
  -h|--help)
    sed -n '2,7p' "$0"
    exit 0
    ;;
esac

if ! command -v "$PASS" >/dev/null 2>&1; then
  echo "Error: \`pass\` not found. Install it or set \$PASS." >&2
  exit 1
fi

gen_env() {
  echo "# Generated by secrets-env.sh — do not edit directly"
  echo "# Use \`pass\` to manage secrets: pass insert|show|rm $PREFIX/<KEY>"
  echo

  find "$STORE/$PREFIX" -name '*.gpg' -maxdepth 1 2>/dev/null | sort | while IFS= read -r path; do
    base=$(basename "$path" .gpg)
    val=$("$PASS" show "$PREFIX/$base" 2>/dev/null | head -1)
    echo "${base}=${val}"
  done
}

if [ -n "$write_to" ]; then
  target_dir=$(dirname "$write_to")
  tmp_file=$(mktemp "$target_dir/.secrets-env.XXXXXX")
  trap 'rm -f "$tmp_file"' EXIT HUP INT TERM
  gen_env > "$tmp_file"
  chmod 600 "$tmp_file"
  mv -f "$tmp_file" "$write_to"
  trap - EXIT HUP INT TERM
  echo "Wrote $write_to with mode 600" >&2
else
  echo "WARNING: printing secrets to stdout" >&2
  gen_env
fi
