#!/bin/sh
# Generate .env from pass password-store for Steward ACS.
# Usage:
#   ./scripts/secrets-env.sh              # print to stdout
#   ./scripts/secrets-env.sh -w           # write directly to .env
#   ./scripts/secrets-env.sh -w .env.prod # write to specific path
set -e

PREFIX="${PASS_PREFIX:-steward}"
PASS="${PASS:-pass}"
STORE="${PASSWORD_STORE_DIR:-$HOME/.password-store}"

write_to=""
case "$1" in
  -w) write_to="${2:-.env}" ;;
  -h|--help)
    sed -n '2,7p' "$0"
    exit 0
    ;;
esac

if ! command -v "$PASS" >/dev/null 2>&1; then
  echo "Error: \`pass\` not found. Install it or set \$PASS." >&2
  exit 1
fi

gen_env() {
  echo "# Generated by secrets-env.sh — do not edit directly"
  echo "# Use \`pass\` to manage secrets: pass insert|show|rm $PREFIX/<KEY>"
  echo

  find "$STORE/$PREFIX" -name '*.gpg' -maxdepth 1 2>/dev/null | sort | while IFS= read -r path; do
    base=$(basename "$path" .gpg)
    val=$("$PASS" show "$PREFIX/$base" 2>/dev/null | head -1)
    echo "${base}=${val}"
  done
}

if [ -n "$write_to" ]; then
  gen_env > "$write_to"
  echo "Wrote $write_to" >&2
else
  gen_env
fi
